import { useState } from "react";
import { Navigation } from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Scan, Shield, Copy, CheckCircle, AlertCircle, Info, ChevronDown, Brain, Lock, Clock, TrendingUp, Download, Zap } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface VerificationResult {
  isAiGenerated: boolean;
  confidence: number;
  blockchainHash: string;
  timestamp: string;
}

export default function Verify() {
  const [text, setText] = useState("");
  const [isVerifying, setIsVerifying] = useState(false);
  const [result, setResult] = useState<VerificationResult | null>(null);
  const { toast } = useToast();

  const handleVerify = async () => {
    if (!text.trim()) return;
    
    setIsVerifying(true);
    
    // Simulate AI verification process
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const mockResult: VerificationResult = {
      isAiGenerated: Math.random() > 0.5,
      confidence: Math.floor(Math.random() * 30) + 70,
      blockchainHash: "0x" + Math.random().toString(16).substring(2, 42),
      timestamp: new Date().toISOString(),
    };
    
    setResult(mockResult);
    setIsVerifying(false);
  };

  const copyHash = () => {
    if (result?.blockchainHash) {
      navigator.clipboard.writeText(result.blockchainHash);
      toast({
        title: "Copied to clipboard",
        description: "Blockchain hash copied successfully",
      });
    }
  };

  const downloadReport = () => {
    if (!result) return;
    
    const reportData = {
      analysis: {
        contentType: result.isAiGenerated ? "AI-Generated" : "Human-Written",
        confidence: `${result.confidence}%`,
        timestamp: new Date(result.timestamp).toLocaleString(),
      },
      blockchain: {
        hash: result.blockchainHash,
        network: "ScanIt Verification Network",
        status: "Verified"
      },
      content: {
        textLength: text.length,
        wordsCount: text.trim().split(/\s+/).length,
        analysisDate: new Date().toLocaleString()
      }
    };

    const reportContent = `
ScanIt Verification Report
==========================

CONTENT ANALYSIS
├─ Classification: ${reportData.analysis.contentType}
├─ Confidence Level: ${reportData.analysis.confidence}
├─ Analysis Date: ${reportData.analysis.timestamp}
├─ Text Length: ${reportData.content.textLength} characters
└─ Word Count: ${reportData.content.wordsCount} words

BLOCKCHAIN VERIFICATION
├─ Hash: ${reportData.blockchain.hash}
├─ Network: ${reportData.blockchain.network}
├─ Status: ${reportData.blockchain.status}
└─ Verification: Permanent & Immutable

CONTENT SAMPLE
${text.slice(0, 500)}${text.length > 500 ? '...' : ''}

---
Generated by ScanIt - AI & Blockchain Content Authenticity Framework
Report ID: ${result.blockchainHash.slice(0, 16)}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scanit-report-${result.blockchainHash.slice(0, 8)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Verification report saved successfully",
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-6">
          {/* Header */}
          <div className="text-center mb-12 animate-fade-in">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-primary mb-6">
              <Scan className="w-8 h-8 text-primary-foreground" />
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              <span className="holographic-text">Verify Content</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Advanced AI detection with blockchain-verified authenticity records
            </p>
          </div>

          {/* Scanner Interface */}
          <div className="max-w-4xl mx-auto">
            <Card className="glass-panel p-8 mb-8">
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium mb-3 text-foreground">
                    Content to Verify
                  </label>
                    <div className="relative">
                      <Textarea
                        value={text}
                        onChange={(e) => setText(e.target.value)}
                        placeholder="Paste your text content here for AI detection analysis..."
                        className="min-h-[200px] bg-muted/50 border-primary/20 focus:border-primary/50 transition-colors"
                      />
                      {isVerifying && (
                        <div className="absolute inset-0 bg-gradient-to-b from-primary/10 via-accent/20 to-primary/10 pointer-events-none rounded-md overflow-hidden">
                          {/* Multiple scanning lines */}
                          <div className="scanner-line h-1 w-full absolute animate-[scanner-sweep_2s_ease-in-out_infinite]" />
                          <div className="scanner-line h-0.5 w-full absolute top-1/3 animate-[scanner-sweep_1.5s_ease-in-out_infinite_0.3s] opacity-60" />
                          <div className="scanner-line h-0.5 w-full absolute top-2/3 animate-[scanner-sweep_1.8s_ease-in-out_infinite_0.6s] opacity-40" />
                          
                          {/* Neural network overlay */}
                          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-primary/5 to-transparent animate-[shimmer_2s_ease-in-out_infinite]" />
                          
                          {/* Corner indicators */}
                          <div className="absolute top-2 left-2 w-4 h-4 border-t-2 border-l-2 border-primary animate-pulse" />
                          <div className="absolute top-2 right-2 w-4 h-4 border-t-2 border-r-2 border-primary animate-pulse delay-150" />
                          <div className="absolute bottom-2 left-2 w-4 h-4 border-b-2 border-l-2 border-primary animate-pulse delay-300" />
                          <div className="absolute bottom-2 right-2 w-4 h-4 border-b-2 border-r-2 border-primary animate-pulse delay-450" />
                          
                          {/* Center pulse */}
                          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                            <div className="w-8 h-8 rounded-full border-2 border-primary/50 animate-ping" />
                            <div className="absolute inset-0 w-4 h-4 m-auto rounded-full bg-primary/30 animate-pulse" />
                          </div>
                        </div>
                      )}
                    </div>
                </div>
                
                <Button
                  onClick={handleVerify}
                  disabled={!text.trim() || isVerifying}
                  size="lg"
                  className={`w-full relative overflow-hidden transition-all duration-500 ${
                    isVerifying 
                      ? 'bg-gradient-to-r from-primary via-accent to-primary bg-[length:200%_100%] animate-[gradient_2s_ease-in-out_infinite] shadow-[0_0_30px_hsl(var(--primary)/0.8)] border-2 border-primary/50' 
                      : 'neon-border bg-gradient-primary hover:shadow-[0_0_40px_hsl(var(--primary)/0.6)] hover:scale-105'
                  }`}
                >
                  {isVerifying && (
                    <>
                      {/* Futuristic overlay effects */}
                      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full animate-[shimmer_1.5s_ease-in-out_infinite]" />
                      <div className="absolute inset-0 opacity-30">
                        <div className="absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-primary to-accent animate-pulse" />
                        <div className="absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-accent to-primary animate-pulse delay-300" />
                      </div>
                      {/* Neural network pulse rings */}
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="w-8 h-8 border-2 border-white/30 rounded-full animate-[ping_1s_ease-in-out_infinite]" />
                        <div className="absolute w-12 h-12 border border-white/20 rounded-full animate-[ping_1.5s_ease-in-out_infinite_0.5s]" />
                        <div className="absolute w-16 h-16 border border-white/10 rounded-full animate-[ping_2s_ease-in-out_infinite_1s]" />
                      </div>
                    </>
                  )}
                  <div className="relative z-10 flex items-center justify-center">
                    {isVerifying ? (
                      <>
                        <div className="flex items-center space-x-3">
                          <Zap className="w-5 h-5 animate-[spin_1s_ease-in-out_infinite] text-white" />
                          <span className="font-bold text-white tracking-wider">ANALYZING NEURAL PATTERNS...</span>
                          <div className="flex space-x-1">
                            <div className="w-2 h-2 bg-white rounded-full animate-bounce" />
                            <div className="w-2 h-2 bg-white rounded-full animate-bounce delay-100" />
                            <div className="w-2 h-2 bg-white rounded-full animate-bounce delay-200" />
                          </div>
                        </div>
                      </>
                    ) : (
                      <>
                        <Scan className="w-5 h-5 mr-2 group-hover:rotate-180 transition-transform duration-300" />
                        <span className="font-bold tracking-wide">VERIFY AUTHENTICITY</span>
                      </>
                    )}
                  </div>
                </Button>
              </div>
            </Card>

            {/* Detailed Information Sections */}
            <div className="space-y-4 mb-8">
              {/* How AI Detection Works */}
              <Collapsible>
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" className="w-full justify-between p-6 h-auto glass-panel">
                    <div className="flex items-center space-x-3">
                      <Brain className="w-5 h-5 text-primary" />
                      <span className="font-medium">How AI Detection Works</span>
                    </div>
                    <ChevronDown className="w-4 h-4" />
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent className="px-6 pb-6">
                  <Card className="bg-muted/30 border-primary/10 p-4 mt-2">
                    <div className="space-y-3 text-sm text-muted-foreground">
                      <p><strong className="text-foreground">Neural Language Models:</strong> Our AI uses advanced transformer architectures trained on millions of human and AI-generated texts to identify subtle patterns that distinguish artificial content.</p>
                      <p><strong className="text-foreground">Multi-Layer Analysis:</strong> The system examines writing patterns, vocabulary usage, sentence structure, and semantic coherence across multiple dimensions.</p>
                      <p><strong className="text-foreground">Real-Time Processing:</strong> Analysis occurs in seconds, providing immediate feedback on content authenticity with detailed confidence metrics.</p>
                    </div>
                  </Card>
                </CollapsibleContent>
              </Collapsible>

              {/* Understanding Confidence Scores */}
              <Collapsible>
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" className="w-full justify-between p-6 h-auto glass-panel">
                    <div className="flex items-center space-x-3">
                      <TrendingUp className="w-5 h-5 text-primary" />
                      <span className="font-medium">Understanding Confidence Scores</span>
                    </div>
                    <ChevronDown className="w-4 h-4" />
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent className="px-6 pb-6">
                  <Card className="bg-muted/30 border-primary/10 p-4 mt-2">
                    <div className="space-y-3 text-sm text-muted-foreground">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="space-y-2">
                          <Badge className="bg-green-500/20 text-green-400 border-green-500/30">90-100%</Badge>
                          <p><strong className="text-foreground">High Confidence:</strong> Very strong indicators present. Result is highly reliable.</p>
                        </div>
                        <div className="space-y-2">
                          <Badge className="bg-yellow-500/20 text-yellow-400 border-yellow-500/30">70-89%</Badge>
                          <p><strong className="text-foreground">Medium Confidence:</strong> Clear patterns identified. Result is reliable but may benefit from human review.</p>
                        </div>
                        <div className="space-y-2">
                          <Badge className="bg-red-500/20 text-red-400 border-red-500/30">50-69%</Badge>
                          <p><strong className="text-foreground">Lower Confidence:</strong> Mixed indicators present. Additional verification recommended.</p>
                        </div>
                      </div>
                    </div>
                  </Card>
                </CollapsibleContent>
              </Collapsible>

              {/* Blockchain Verification Details */}
              <Collapsible>
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" className="w-full justify-between p-6 h-auto glass-panel">
                    <div className="flex items-center space-x-3">
                      <Lock className="w-5 h-5 text-primary" />
                      <span className="font-medium">Blockchain Verification Details</span>
                    </div>
                    <ChevronDown className="w-4 h-4" />
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent className="px-6 pb-6">
                  <Card className="bg-muted/30 border-primary/10 p-4 mt-2">
                    <div className="space-y-3 text-sm text-muted-foreground">
                      <p><strong className="text-foreground">Immutable Records:</strong> Every verification is recorded on the blockchain, creating a permanent, tamper-proof record of the analysis.</p>
                      <p><strong className="text-foreground">Cryptographic Hash:</strong> The unique hash serves as a digital fingerprint, allowing anyone to verify the authenticity and timestamp of the analysis.</p>
                      <p><strong className="text-foreground">Transparency:</strong> All verification records are publicly accessible, enabling independent verification and building trust in the system.</p>
                      <p><strong className="text-foreground">Audit Trail:</strong> The blockchain provides a complete history of content verification, supporting forensic analysis and accountability.</p>
                    </div>
                  </Card>
                </CollapsibleContent>
              </Collapsible>
            </div>

            {/* Results */}
            {result && (
              <Card className="glass-panel p-8 animate-fade-in">
                <div className="space-y-6">
                  <div className="flex items-center space-x-3 mb-6">
                    <div className="w-12 h-12 rounded-full bg-gradient-primary flex items-center justify-center">
                      <Shield className="w-6 h-6 text-primary-foreground" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold">Verification Complete</h3>
                      <p className="text-muted-foreground">Analysis results below</p>
                    </div>
                  </div>

                  {/* AI Detection Result */}
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-6 rounded-lg bg-muted/30 border border-primary/20">
                      <div className="flex items-center space-x-4">
                        {result.isAiGenerated ? (
                          <AlertCircle className="w-8 h-8 text-destructive" />
                        ) : (
                          <CheckCircle className="w-8 h-8 text-primary" />
                        )}
                        <div>
                          <p className="font-semibold text-lg">
                            {result.isAiGenerated ? "AI-Generated Content" : "Human-Written Content"}
                          </p>
                          <p className="text-muted-foreground">
                            Confidence: {result.confidence}%
                          </p>
                        </div>
                      </div>
                      <Badge 
                        variant={result.isAiGenerated ? "destructive" : "default"}
                        className="px-4 py-2 text-sm font-medium animate-hologram-flicker"
                      >
                        {result.isAiGenerated ? "AI Detected" : "Human Verified"}
                      </Badge>
                    </div>

                    {/* Detailed Result Explanation */}
                    <Card className="bg-accent/5 border-accent/20 p-4">
                      <div className="flex items-start space-x-3">
                        <Info className="w-5 h-5 text-accent mt-0.5" />
                        <div className="space-y-2 text-sm">
                          <h4 className="font-medium text-foreground">What This Means:</h4>
                          {result.isAiGenerated ? (
                            <div className="space-y-2 text-muted-foreground">
                              <p><strong className="text-foreground">AI-Generated Detection:</strong> Our analysis indicates this content was likely produced by an artificial intelligence system.</p>
                              <p><strong className="text-foreground">Key Indicators:</strong> Pattern recognition suggests artificial linguistic patterns, repetitive structures, or lack of human-specific nuances.</p>
                              <p><strong className="text-foreground">Recommended Actions:</strong> Verify source, cross-reference with known publications, consider requesting original authorship documentation.</p>
                            </div>
                          ) : (
                            <div className="space-y-2 text-muted-foreground">
                              <p><strong className="text-foreground">Human-Written Verification:</strong> Analysis suggests this content exhibits natural human writing characteristics.</p>
                              <p><strong className="text-foreground">Key Indicators:</strong> Natural flow, human-specific expressions, creative variations, and authentic voice patterns detected.</p>
                              <p><strong className="text-foreground">Confidence Level:</strong> High likelihood of authentic human authorship based on linguistic analysis.</p>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  </div>

                  {/* Blockchain Record */}
                  <div className="space-y-4">
                    <div className="p-6 rounded-lg bg-gradient-glass border border-accent/30">
                      <div className="flex items-center justify-between">
                        <div className="space-y-2">
                          <p className="font-semibold text-accent">Blockchain Verification</p>
                          <p className="text-sm text-muted-foreground font-mono">
                            {result.blockchainHash}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            Verified: {new Date(result.timestamp).toLocaleString()}
                          </p>
                        </div>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={copyHash}
                          className="border-accent/50 hover:bg-accent/10"
                        >
                          <Copy className="w-4 h-4 mr-2" />
                          Copy Hash
                        </Button>
                      </div>
                    </div>

                    {/* Blockchain Explanation */}
                    <Card className="bg-secondary/5 border-secondary/20 p-4">
                      <div className="flex items-start space-x-3">
                        <Clock className="w-5 h-5 text-secondary mt-0.5" />
                        <div className="space-y-2 text-sm">
                          <h4 className="font-medium text-foreground">Blockchain Record Details:</h4>
                          <div className="space-y-2 text-muted-foreground">
                            <p><strong className="text-foreground">Permanent Record:</strong> This verification is now permanently stored on the blockchain and cannot be altered or deleted.</p>
                            <p><strong className="text-foreground">Hash Usage:</strong> Use this hash to independently verify this analysis result at any time. Share it as proof of verification.</p>
                            <p><strong className="text-foreground">Timestamp Proof:</strong> The blockchain timestamp proves when this verification occurred, providing temporal authenticity.</p>
                            <p><strong className="text-foreground">Audit Trail:</strong> This record contributes to a comprehensive audit trail for content authenticity tracking.</p>
                          </div>
                        </div>
                      </div>
                    </Card>
                  </div>

                  {/* Download Report Button */}
                  <div className="pt-6 border-t border-border/50">
                    <Button
                      onClick={downloadReport}
                      variant="outline"
                      size="lg"
                      className="w-full bg-gradient-to-r from-secondary/20 to-accent/20 hover:from-secondary/30 hover:to-accent/30 border-accent/40 hover:border-accent/60 text-foreground hover:text-white transition-all duration-300 neon-border"
                    >
                      <Download className="w-5 h-5 mr-2" />
                      <span className="font-semibold">Download Verification Report</span>
                    </Button>
                  </div>
                </div>
              </Card>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}