// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehlqlznsnbkyikijomnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobHFsem5zbmJreWlraWpvbW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTI1MTgsImV4cCI6MjA3MjgyODUxOH0.3VY4iXbPPaQRXv_AhuxnxqZ1FluksTDVtZko06TD2EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});